### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by rcrath** [nbeaver/recoll-status#1]
Thanks for this.  It is just what I need, unfortunately, (a) I don't know how to code well enough to fix it and (b) I get the following error when I run it:

```
rich[~]$ ~/git/recoll-status/recoll-status.sh 
recollindex is running.
 recollindex has been running for 0 days 0 hours 34 minutes 37 seconds
  File "/home/rich/git/recoll-status/parse-idxstatus.py", line 20
    print 'DblxStatus is',DblxStatus[val]
                        ^
SyntaxError: Missing parentheses in call to 'print'

```

**Comment by nbeaver** [comment]
I neglected to make it work with Python 3. This should have fixed it: https://github.com/nbeaver/recoll-status/commit/ee4f54e4559d7fb1e129c1b0b9377d7d526f87c9

Let me know if it works now.

**Comment by nbeaver** [comment]
I'm going to close the issue because it's fixed on my end.

**Comment by rcrath** [comment]
thanks. will try.

**Comment by rcrath** [comment]
works. thanks!
