### ISSUE TITLE
How to fix:  ValueError: need more than 1 value to unpack

### ISSUE THREAD

**Issue by afm-mike** [nbeaver/recoll-status#2]
Traceback (most recent call last):
  File "/home/pete/parse-idxstatus.py", line 19, in <module>
    key, val = (x.strip() for x in line.split('='))
ValueError: need more than 1 value to unpack

Does not span split line correctly, sees as 2 lines:

fn = /data/archived_data/private/pete/Rudde, \
Sally/data home/attachmentZ.tiff

**Comment by nbeaver** [comment]
Interesting, I've never seen it split over two lines like that.

Could you upload the full `idxstatus.txt` file somewhere and link to it?

Also, what version of `recoll` are you using?

**Comment by nbeaver** [comment]
I believe I have fixed the problem with continuation lines here:

https://github.com/nbeaver/recoll-status/commit/8de5ae380beaba19da3130ab98203bdccb3c1055

I've also added an idxstatus file with continuation lines here:

https://github.com/nbeaver/recoll-status/blob/master/idxstatuses/004.txt

Let me know if this problem re-occurs, but I'm closing this for now.
